version: 2

project_name: webtoon-dl

before:
  hooks:
    - go mod tidy

builds:
  - binary: webtoon-dl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows

archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: robinovitch61
    name: webtoon-dl

brews:
  - name: webtoon-dl
    homepage: https://github.com/robinovitch61/webtoon-dl
    description: "A cli for downloading content from webtoon.com"
    directory: Formula
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: robinovitch61
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

winget:
  - name: webtoon-dl
    publisher: robinovitch61
    license: MIT
    copyright: "Leo Robinovitch"
    homepage: https://github.com/robinovitch61/webtoon-dl
    short_description: "A cli for downloading content from webtoon.com"
    package_identifier: "robinovitch61.webtoon-dl"
    repository:
      owner: "robinovitch61"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

scoops:
  - repository:
      owner: "robinovitch61"
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@theleo.zone
    homepage: https://github.com/robinovitch61/webtoon-dl
    description: "A cli for downloading content from webtoon.com"
    license: MIT

chocolateys:
  - owners: "Leo Robinovitch"
    authors: "Leo Robinovitch"
    project_url: https://github.com/robinovitch61/webtoon-dl
    url_template: "https://github.com/robinovitch61/webtoon-dl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license_url: https://github.com/robinovitch61/webtoon-dl/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/robinovitch61/webtoon-dl
    docs_url: https://github.com/robinovitch61/webtoon-dl/blob/main/README.md
    bug_tracker_url: https://github.com/robinovitch61/webtoon-dl/issues
    tags: "webtoon webtoon-dl comics manga"
    summary: "A cli for downloading content from webtoon.com"
    description: |
      # A cli for downloading content from webtoon.com

      Download webtoon comics as PDFs using a terminal/command line.
    release_notes: "https://github.com/robinovitch61/webtoon-dl/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false

gomod:
  proxy: true
